### ISSUE TITLE
Read the docs site for minute

### ISSUE THREAD

**Issue by cnluzon** [elsasserlab/minute#172]
I feel like ways to run minute are growing a bit and maybe it would be a good approach to start a proper "read the docs" site to include all possible information about how to use the workflow.

**Comment by marcelm** [comment]
For a new project, I’d probably try to use [MkDocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html) over Sphinx since it uses Markdown instead of ReST.
