### ISSUE TITLE
bw file output choice

### ISSUE THREAD

**Issue by simonelsasser** [elsasserlab/minute#40]
It's always problematic to create too many alternative output files by default (see TDF thread), but in the case of bw files it may make sense to create at least two:

1) _including_ multimappers, _excluding_ blacklisted regions, scaled
2) _excluding_ multimappers (MQ>0), _excluding_ blacklisted regions, scaled

then I previously used a "lowres" ("supersmooth") version for IGV visualisation since IGV has a problem with visualising regions with scarce reads properly. There is no easy way to create a smoothened bw file out of an existing bw file unfortunately (all bwtools, WiggleTools etc can read bw but not write a bw). If there was I would say we can always create it ad hoc.

3) _including_ multimappers, _excluding_ blacklisted regions, _smoothened_ and _binned_, scaled

Regarding blacklisting, there are in principle two ways, 1) remove reads from BAM file, 2) remove regions during bw file generation. I would prefer option 2) since then the BAM file is untouched and can be used for any purpose including to read out repetitive region enrichments. However, bamCoverage crashed on me when I tried to specify a blacklist file before. Please see if it works for you.

**Comment by cnluzon** [comment]
I am closing this one also, the multimapping was now fully adressed in #173 , blacklisting was already included and the smoothing does not always have the values we expect. Smoothened bigWigs we rarely generate and they can always still be manually generated from the BAM.
