### ISSUE TITLE
Which bigwig files to produce

### ISSUE THREAD

**Issue by simonelsasser** [elsasserlab/minute#64]
@cnluzon in reference to the other thread on repeats, I wonder what the optimal minimal output of scaled bigwig files using bamCoverage would be. We want to produce several different versions so we cover a range of possible downstream analyses without having to go back to. But obviously not too many because then it becomes confusing. So my thinking is:

**1)** scaled bigwig, basepair resolution, no blacklisting
**parameters**: -bs 1
**good for**: count-based analysis e.g. **bw_bed** and **bw_bed** where most accurate analysis is needed and where values are typically normalized by matched input track
**not good for**: plotting and heatmaps, because some extreme values from repetitive regions may offset the whole plot
**good for**: special plotting, e.g. IAP ERVs or MinSat, where repetitive regions are included intentionally

**2)** scaled bigwig, 5bp resolution, blacklisted, uniquely mappable reads only
**parameters**: -bs 5 / samtools MQ > 10
**good for**: plotting and heat maps
**good for**: count-based analysis e.g. **bw_bed** and **bw_bed** (-bs 5 versus 1 doesn't really matter in most cases)

**3)** scaled bigwig, 5bp resolution, blacklisted, all reads, paired end fragments filled in
**parameters**: -bs 5 -e
**good for**: plotting and heat maps where the focus is on the position of nucleosome or factors (for this it is important to pile up the entire paired-end fragments not just the left and right sequenced part.
**good for**: plotting and heat maps of ERVs

**4)** scaled bigwig, 50bp resolution, smoothened, blacklisted, all reads, paired end fragments filled in
**parameters**: -bs 50 --smoothLength 150 -e 
**good for**: IGV visualisation

obviosuly, there's still some specialty cases that are not covered by those four options. E.g. if one would want to produce two *exact* equivalent plots, one with only unique and one including multimap reads. But I think the differences are ultimately very minor.

**Comment by cnluzon** [comment]
This one is also resolved on #173, at least the main multimapping filtering functions we have sometimes needed. Generally we always use `--extendReads` parameter so if there is a specific need not to do it it should probably be argued in a separate issue.
